# Generated by Django 4.1.3 on 2022-11-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_Name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_id', models.CharField(default='', max_length=100)),
                ('firstName', models.CharField(default='', max_length=100)),
                ('middleName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=10)),
                ('year', models.IntegerField()),
                ('totalFees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_id', models.IntegerField()),
                ('scholarship_name', models.CharField(default='', max_length=100)),
                ('sponsor', models.CharField(default='', max_length=100)),
                ('accountNumber', models.CharField(default='', max_length=100)),
                ('totalScholars', models.IntegerField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.bank')),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarshipType_id', models.IntegerField()),
                ('scholarshipType_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarType_id', models.IntegerField()),
                ('scholarType_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeAssigned', models.CharField(default='', max_length=100)),
                ('scholar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholar')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy', models.FloatField()),
                ('scholarship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholarship')),
            ],
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholarshiptype'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='scholar_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholartype'),
        ),
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('scholarship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='NonWorking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholar')),
                ('scholarship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.scholarship')),
            ],
        ),
    ]
